version: '2'

services:
  vreceiver:
    container_name: vreceiver
    command: omxplayer -o hdmi tcp://${RECEIVE_IP}:5001
    image: pavelis/omxplayer
    restart: always
    privileged: true
    tty: true
    environment:
      - DISPLAY=:0
    devices:
      - "/dev/vchiq:/dev/vchiq"

  vsender:
    container_name: vsender
    command: bash -c 'gst-launch-1.0 -v -m v4l2src device=/dev/video0 ! queue ! video/x-h264,width=1920,height=1080,framerate=24/1 ! fdsink | nc -l 5001'
    image: pavelis/gstreamer
    restart: always
    privileged: true
    tty: true
    environment:
      - DISPLAY=:0
    ports:
      - ${VIDEO_PORT}:5001/tcp
    devices:
      - "${VIDEO_DEV}:/dev/video0"

  areceiver:
    container_name: areceiver
    command: gst-launch-1.0 -v udpsrc port=5003 caps="application/x-rtp,channels=1" ! queue ! rtpjitterbuffer latency=100  ! rtpopusdepay ! opusdec plc=true ! queue ! audioconvert ! audioresample ! alsasink device=${ALSA_OUT_DEV}
    image: pavelis/gstreamer
    restart: always
    privileged: true
    tty: true
    environment:
      - DISPLAY=:0
    ports:
      - ${AUDIO_PORT}:5003/udp
    devices:
      - "/dev/snd:/dev/snd"

  asender:
    container_name: asender
    command: gst-launch-1.0 -v alsasrc device=${ALSA_IN_DEV} ! queue ! audiorate ! audioconvert ! audioresample ! opusenc ! rtpopuspay ! udpsink host=${RECEIVE_IP} port=5003
    image: pavelis/gstreamer
    restart: always
    privileged: true
    tty: true
    environment:
      - DISPLAY=:0
    devices:
      - "/dev/snd:/dev/snd"

