version: '2'

services:
  reciveVideo:
    container_name: reciveVideo
#    command: bash -c 'rm -f video.stream  && mkfifo video.stream && nc   -l 5001 > video.stream | omxplayer -o hdmi video.stream'
    command: bash -c 'rm -f video.stream  && mkfifo video.stream && nc -u -l 5001 > video.stream | omxplayer -o hdmi video.stream'
    image: marat2501/omxpalyer
    restart: always
    privileged: true
    tty: true
    environment:
      - DISPLAY=:0
    ports:
      - ${VIDEO_PORT}:5001/tcp
      - ${VIDEO_PORT}:5001/udp
    devices:
      - "/dev/vchiq:/dev/vchiq"

  sendVideo:
    container_name: sendVideo
    command: bash -c 'gst-launch-1.0 -v  v4l2src device=/dev/video0 ! queue ! video/x-h264,width=1920,height=1080,framerate=24/1 ! fdsink | nc -u ${RECEIVE_IP} 5001'
    image: marat2501/gstreamer
    restart: always
    privileged: true
    tty: true
    environment:
      - DISPLAY=:0
    devices:
      - "${VIDEO_DEV}:/dev/video0"

  reciveAudio:
    container_name: reciveAudio
    command: gst-launch-1.0 -v udpsrc port=5003 caps="application/x-rtp,channels=1" ! queue ! rtpjitterbuffer latency=100  ! rtpopusdepay ! opusdec plc=true ! queue ! audioconvert ! audioresample ! alsasink device=${ALSA_OUT_DEV}
    image: marat2501/gstreamer
    restart: always
    privileged: true
    tty: true
    environment:
      - DISPLAY=:0
    ports:
      - ${AUDIO_PORT}:5003/udp
    devices:
      - "/dev/snd:/dev/snd"

  sendAudio:
    container_name: sendAudio
    command: gst-launch-1.0 -v alsasrc device=${ALSA_IN_DEV} ! queue ! audiorate ! audioconvert ! audioresample ! opusenc ! rtpopuspay ! udpsink host=${RECEIVE_IP} port=5003
    image: marat2501/gstreamer
    restart: always
    privileged: true
    tty: true
    environment:
      - DISPLAY=:0
    devices:
      - "/dev/snd:/dev/snd"
