FROM resin/rpi-raspbian:jessie

# Install basics
## Use the "noninteractive" debconf frontend
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get -y --no-install-recommends upgrade \
    && apt-get -y --no-install-recommends install wget sudo 

# Install video tools
RUN apt-get -y --no-install-recommends install \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-base-apps \
    gstreamer1.0-plugins-good \
    gstreamer1.0-tools \
    gstreamer1.0-alsa \
    gir1.2-gst-plugins-base-1.0 \
    gir1.2-gstreamer-1.0 \
    v4l-utils \
    libraspberrypi-bin \
    libraspberrypi-dev \
    netcat-openbsd \
    netcat-traditional \ 
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

